#!/bin/sh

GetOldTweetsExporterPython=$1;
GetOldTweetsExporterFile=$2;

if [ ! -f "$GetOldTweetsExporterPython" -o ! -f "$GetOldTweetsExporterFile" ]; then
  echo "usage: $0 <path_to_python> <path_to_Exporter.py>"
  echo "Get Exporter.py from https://github.com/Jefferson-Henrique/GetOldTweets-python"
  exit
fi

combinedFile='combined.tmp.csv';
goFile='tweetarchive_gen.go';
echo 'username;date;retweets;favorites;text;geo;mentions;hashtags;id;permalink' > $combinedFile;

for screenName in 'BarackObama' 'POTUS44' 'realDonaldTrump' 'POTUS'; do
  targetFile=$screenName.tmp.csv;
  echo "--- Downloading tweets for @$screenName...";
  # use --maxtweets N to limit tweets
  $GetOldTweetsExporterPython $GetOldTweetsExporterFile \
    --username $screenName \
    --output $targetFile;
  echo "--- Wrote $targetFile.";
  echo "--- Appending to $combinedFile..."
  tail -n +2 $targetFile >> $combinedFile;
  echo "" >> $combinedFile;
  echo "--- Appended."
  rm $targetFile;
  echo "--- Deleted $targetFile.";
done

echo "--- Patching $combinedFile to fix ambiguous CSV..."
sed 's/"";/" ";/' $combinedFile > /tmp/patched-combined.csv;
mv /tmp/patched-combined.csv $combinedFile;

echo "--- Re-reading $combinedFile.";
csvBody="$(cat "$combinedFile")";
echo "--- Generating $goFile.";

echo "package migrations

// DO NOT EDIT! Generated by ./generate_archive.sh

const tweetArchiveCSV = \`$csvBody\`
" > $goFile;

echo "--- Done. Removing $combinedFile and exiting."
rm $combinedFile;
